apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}{{ .Values.nameSuffix }}
  labels:
    app: {{ .Chart.Name }}{{ .Values.nameSuffix }}
  namespace: showks-system
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}{{ .Values.nameSuffix }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}{{ .Values.nameSuffix }}
    spec:
      containers:
      - name: {{ .Chart.Name }}{{ .Values.nameSuffix }}
        image: cloudnativedaysjp/{{ .Chart.Name }}:{{ .Values.image.tag }}
        env:
          - name: RAILS_ENV
            value: "production"
          - name: RAILS_SERVE_STATIC_FILES
            value: "true"
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: masterkey
                key: masterkey
          - name: RAILS_LOG_TO_STDOUT
            value: "true"
        ports:
        - containerPort: 3000

