apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}{{ .Values.nameSuffix }}
  namespace: showks
  labels:
    app: {{ .Chart.Name }}{{ .Values.nameSuffix }}
spec:
  replicas: 
  selector:
    matchLabels:
      app: {{ .Chart.Name }}{{ .Values.nameSuffix }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}{{ .Values.nameSuffix }}
    spec:
      containers:
        - name: {{ .Chart.Name }}{{ .Values.nameSuffix }}
          image: gcr.io/ipc-containerdays/{{ .Chart.Name }}:{{ .Values.image.tag }}
          env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: showks-config
                  key: domain
            - name: AGGREGATOR_URL
              value: https://aggregator$(DOMAIN)
          ports:
            - name: app-port
              containerPort: 3000
              protocol: TCP

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}{{ .Values.nameSuffix }}
  labels:
    app: {{ .Chart.Name }}{{ .Values.nameSuffix }}
  namespace: showks
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}{{ .Values.nameSuffix }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}{{ .Values.nameSuffix }}
    spec:
      containers:
      - name: {{ .Chart.Name }}{{ .Values.nameSuffix }}
        image: gcr.io/ipc-containerdays/{{ .Chart.Name }}:{{ .Values.image.tag }}
        env:
          - name: RAILS_ENV
            value: "production"
          - name: DB_HOST
            value: "mysql.showks.svc.cluster.local"
          - name: DB_USERNAME
            value: "root"
          - name: DB_PASSWORD
            value: "passw0rd"
          - name: DB_DATABASE
            value: "showks"
          - name: RAILS_SERVE_STATIC_FILES
            value: "true"
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: masterkey
                key: masterkey
          - name: RAILS_LOG_TO_STDOUT
            value: "true"
        lifecycle:
          postStart:
            exec:
              command:
                - /usr/src/showks-form/post-start.sh
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: showks
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: passw0rd
        - name: MYSQL_DATABASE
          value: showks
        args: ["--ignore-db-dir=lost+found"]
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysqld-config
          mountPath: /etc/mysql/mysql.conf.d/
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysqld-config
        configMap:
          name: mysqld-config
