apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: showks
  labels:
    app: showks-form
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
