---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Chart.Name }}-access
  namespace: showks-system
rules:
- apiGroups: ["","apps","extensions"]
  resources: ["services","deployments","ingresses", "pods", "secrets"]
  verbs: ["*"]
- apiGroups: ["showks.cloudnativedays.jp"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["argoproj.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-access-binding
  namespace: showks-system
subjects:
- kind: ServiceAccount
  name: default
  namespace: showks-system
roleRef:
  kind: ClusterRole
  name: {{ .Chart.Name }}-access
  apiGroup: rbac.authorization.k8s.io
