---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Chart.Name }}-access
  namespace: showks-system
rules:
- apiGroups: ["","apps","extensions"]
  resources: ["services","deployments","ingresses", "pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["showks.cloudnativedays.jp/v1beta1"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["argoproj.io/v1alpha1"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-access-binding
  namespace: showks-system
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: {{ .Chart.Name }}-access
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Chart.Name }}-access
  namespace: showks
rules:
- apiGroups: ["","apps","extensions"]
  resources: ["services","deployments","ingresses", "pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["showks.cloudnativedays.jp/v1beta1"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["argoproj.io/v1alpha1"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-access-binding
  namespace: showks
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: {{ .Chart.Name }}-access
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Chart.Name }}-access
  namespace: argocd
rules:
- apiGroups: ["","apps","extensions"]
  resources: ["services","deployments","ingresses", "pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["argoproj.io/v1alpha1"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-access-binding
  namespace: showks-system
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: {{ .Chart.Name }}-access
  apiGroup: rbac.authorization.k8s.io
