apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}{{ .Values.nameSuffix }}
  namespace: showks
  labels:
    app: {{ .Chart.Name }}{{ .Values.nameSuffix }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: app-port
  selector:
    app: {{ .Chart.Name }}{{ .Values.nameSuffix }}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: showks
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
