resources:
- name: app
  type: git
  check_every: 600h
  webhook_token: ((github_webhook_token))
  source:
    uri: https://github.com/cloudnativedaysjp/showks-canvas-USERNAME
    branch: master

- name: app-staging
  type: git
  source:
    uri: https://github.com/cloudnativedaysjp/showks-canvas-USERNAME
    branch: staging

- name: concourse-pipelines
  type: git
  source:
    uri: https://github.com/cloudnativedaysjp/showks-concourse-pipelines
    branch: master

- name: k8s-manifests
  type: git
  source:
    uri: git@github.com:cloudnativedaysjp/showks-manifests-prod.git
    branch: master
    private_key: GITHUB_PRIVATE_KEY

- name: container-image
  type: docker-image
  source:
    repository: cloudnativedaysjp/showks-canvas-USERNAME
    username: ((registry_user))
    password: ((registry_password))

jobs:
- name: push-image
  plan:
  - get: app-staging
  - get: app
    trigger: true
  - get: container-image
    params:
      tag_file: app-staging/.git/refs/heads/staging
      tag_prefix: stg-
      save: true
  - put: container-image
    params:
      load: container-image
      tag_file: app/.git/refs/heads/master
      tag_prefix: prod-
- name: upload-manifest
  plan:
  - get: app
    trigger: true
    passed: ["push-image"]
  - get: k8s-manifests
  - get: concourse-pipelines
  - task: update-manifest
    file: concourse-pipelines/common/tasks/upload_manifest_s3.yaml
    params:
      APP_NAME: showks-canvas-USERNAME
      TAG_PREFIX: prod-
      BRANCH: master
      USERID: USERNAME
      VHOST_DOMAIN: .showks.cloudnativedays.jp
      PROJECT_NAME: ipc-containerdays
      AWS_ACCESS_KEY_ID: ((storage_access_key))
      AWS_SECRET_ACCESS_KEY: ((storage_secret_key))
      AWS_DEFAULT_REGION: ap-northeast-1
